#!/bin/bash
# This is intended to be run as a daemon in order to keep a
#  CVMFS configuration repository mounted indefinitely on Debian.
#  It is to work around the fact that Debian's autofs does not allow
#  recursive mounts.
ME="`basename $0`"
usage()
{
    echo "Usage: $ME [-p pidfile] directory_to_mount" >&2
    exit 1
}

if [ "$1" = "-p" ] && [ -n "$2" ]; then
    echo $$ >$2
    shift 2
fi
if [ -z "$1" ]; then
    usage
fi
set -e
cd "$1"
exec -a $ME sleep infinity
